#!/usr/bin/env zsh

successfully() {
  $* || (echo "failed" 1>&2 && exit 1)
}

echo "Pulling dotfiles repo ..."
  successfully cd ~ && git clone git@github.com:megalithic/dotfiles.git

echo "Checking for SSH key, generating one if it doesn't exist ..."
  [[ -f ~/.ssh/id_rsa.pub ]] || ssh-keygen -t rsa

echo "Copying public key to clipboard. Paste it into your Github account ..."
  [[ -f ~/.ssh/id_rsa.pub ]] && cat ~/.ssh/id_rsa.pub | pbcopy
  successfully open https://github.com/account/ssh

echo "Fixing permissions ..."
  successfully sudo chown -R `whoami` /usr/local

echo "Installing Homebrew, a good OS X package manager ..."
  successfully ruby <(curl -fsS https://raw.github.com/mxcl/homebrew/go)
  successfully brew update

echo "Putting Homebrew location earlier in PATH ..."
  successfully echo "
# recommended by brew doctor
export PATH='/usr/local/bin:$PATH'" >> ~/.zshenv
  successfully source ~/.zshenv

echo "Installing GNU Compiler Collection and dependencies ..."
  successfully brew tap homebrew/dupes
  successfully brew install autoconf automake apple-gcc42

echo "Installing oh-my-zsh ..."
  successfully curl -L https://github.com/robbyrussell/oh-my-zsh/raw/master/tools/install.sh | sh

echo "Installing libksba, recommended for Ruby 1.9.3 ..."
  successfully brew install libksba

echo "Installing Postgres, a good open source relational database ..."
  successfully brew install postgres --no-python
  successfully initdb /usr/local/var/postgres -E utf8

echo "Installing Redis, a good key-value database ..."
  successfully brew install redis

echo "Installing ack, for searching the contents of files ..."
  successfully brew install ack

echo "Installing ctags, for indexing files for vim tab completion of methods, classes, variables ..."
  successfully brew install ctags

echo "Installing tmux, for saving project state and switching between projects; also install tmux-powerline ..."
  successfully brew install tmux

echo "Installing reattach-to-user-namespace, for copy-paste and RubyMotion compatibility with tmux ..."
  successfully brew install reattach-to-user-namespace

echo "Installing ImageMagick, for cropping and re-sizing images ..."
  successfully brew install imagemagick

echo "Installing QT, used by Capybara Webkit for headless Javascript integration testing ..."
  successfully brew install qt

echo "Installing watch, used to execute a program periodically and show the output ..."
  successfully brew install watch

echo "Installing the rest of the stuff ..."
  brew install git vim macvim python python3 mysql node yeoman weechat zsh-lovers zsh-completions jshint ffind gist git-flow hub sshfs wget ffmpeg sqlite grep

echo "Installing RVM (Ruby Version Manager) and Ruby 1.9.3-p327, which becomes the default ..."
  successfully curl -L https://get.rvm.io | bash -s stable --ruby
  successfully echo "
# RVM
[[ -s '/Users/`whoami`/.rvm/scripts/rvm' ]] && source '/Users/`whoami`/.rvm/scripts/rvm'" >> ~/.zshenv
  successfully source ~/.rvm/scripts/rvm

echo "Installing critical Ruby gems for Rails development ..."
  successfully gem install bundler rails pg foreman thin --no-rdoc --no-ri

# echo "Installing standalone Heroku CLI client. You'll need administrative rights on your machine ..."
#   successfully curl -s https://toolbelt.heroku.com/install.sh | sh

# echo "Installing the heroku-config plugin for pulling config variables locally to be used as ENV variables ..."
#   successfully /usr/local/heroku/bin/heroku plugins:install git://github.com/ddollar/heroku-config.git

echo "Symlinking zsh and oh-my-zsh files ..."
  successfully ln -s ~/dotfiles/zsh/zshrc ~/.zshrc
  successfully ln -s ~/dotfiles/zsh/zshrc.functions ~/.zshrc.functions
  successfully ln -s ~/dotfiles/zsh/zshrc.aliases ~/.zshrc.aliases
  successfully ln -s ~/dotfiles/zsh/zshrc.keybindings ~/.zshrc.keybindings
  successfully ln -s ~/dotfiles/zsh/replicant.zsh-theme ~/.oh-my-zsh/themes/replicant.zsh-theme

echo "Symlinking vim files and directories ..."
  successfully ln -sf ~/dotfiles/vim ~/.vim
  successfully ln -s ~/dotfiles/vim/vimrc ~/.vimrc
  successfully ln -s ~/dotfiles/vim/vimrc.functions ~/.vimrc.functions.vim
  successfully ln -s ~/dotfiles/vim/vimrc.keybindings ~/.vimrc.keybindings.vim
  successfully ln -s ~/dotfiles/vim/vimrc.mainsettings ~/.vimrc.mainsettings.vim
  successfully ln -s ~/dotfiles/vim/vimrc.pluginsettings ~/.vimrc.pluginsettings.vim

echo "Symlinking tmux and teamocil files ..."
  successfully ln -sf ~/dotfiles/tmux/tmux.conf ~/.tmux.conf
  successfully ln -sf ~/dotfiles/tmux/tmux-powerlinerc.replicant ~/.tmux-powerlinerc
  successfully ln -sf ~/dotfiles/tmux/teamocil ~/.teamocil

echo "Symlinking weechat directory ..."
  successfully ln -sf ~/dotfiles/weechat ~/.weechat

echo "Symlinking git files ..."
  successfully ln -s ~/dotfiles/git/gitrc ~/.gitrc

echo "Symlinking ack files ..."
  successfully ln -s ~/dotfiles/ack/ackrc ~/.ackrc

echo "Symlinking gem files ..."
  successfully ln -s ~/dotfiles/gemrc ~/.gemrc

echo "Symlinking misc other files and directories ..."
  # so we have common apache functionality with other nix distros
  successfully ln -s /Library/WebServer/Documents /var/www

echo "Your shell will now restart in order for changes to apply."
  exec $SHELL -l
